# Site settings
title: "Mortal Game"
description: "So I was feeling nostalgic."
baseurl: "https://determinate.github.io/typewriter"
url: "https://determinate.github.io/typewriter"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
