# Site settings
title: "Смертельная игра"
description: "Quantic Dream style."
baseurl: "https://determinate.github.io/typewriter"
url: "https://determinate.github.io/typewriter"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 10

# Links
links:
  - title: "abt"
    url: /about
