# Site settings
title: "Mortal Game"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://determinate.github.io/typewriter/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "git"
    url: http://github.com/determinate
  - title: "rss"
    url: /feed.xml
